### ISSUE TITLE
[FEATURE] Styling improvement

### ISSUE THREAD

**Issue by siiddhantt** [swapnilsparsh/hacktoberfest-swag#1]
Styling of the list itself can be improved. It's very basic as of right now. Can I be assigned this for HacktoberFest 2022?

**Comment by swapnilsparsh** [comment]
> Styling of the list itself can be improved. It's very basic as of right now. Can I be assigned this for HacktoberFest 2022?

Good Luck 👍🏻
Here is a design from which you can take idea:
![Screenshot 2022-09-14 211811](https://user-images.githubusercontent.com/69387608/192528260-7611f42d-0751-40d3-8434-93e08fd7da45.png)

**Comment by siiddhantt** [comment]
I've made a PR for the enhancement of this.

**Comment by swapnilsparsh** [comment]
> I've made a PR for the enhancement of this.

You have made a seperate grid for this but I want it intside the company swag card.

**Comment by siiddhantt** [comment]
Oh I thought it was supposed to be a filter-by-tag implementation. So I've added it at the top. Can do the separate one, but will that count as spam if I made a PR of that?
