### ISSUE TITLE
Separate pages for previous Hacktoberfest

### ISSUE THREAD

**Issue by swapnilsparsh** [swapnilsparsh/hacktoberfest-swag#30]
Using the commit history add pages for previous Hacktoberfest from the data which is there in the repo.

**Comment by Yashwanth-Chandrakumar** [comment]
Can you assign it to me because i have comeup with a solution.
![image](https://github.com/user-attachments/assets/4450e17f-4836-48c8-9436-46fa08935782)

**Comment by Yashwanth-Chandrakumar** [comment]
@swapnilsparsh why is this repo marked excluded in Hacktober 2024

**Comment by swapnilsparsh** [comment]
> @swapnilsparsh why is this repo marked excluded in Hacktober 2024

Don't know
